#!name= 签到脚本Cookie获取
#!desc= 从 Quantumult X/JS_GetCookie.conf 翻译，Cookie 获取后建议禁用本插件并移除相关 hostname。
#!author= PoetryU

hostname = ms.jr.jd.com, me-api.jd.com, api.m.jd.com, passport.iqiyi.com, music.163.com, *.v2ex.com, *.video.qq.com, wapside.189.cn, i.meituan.com, node.kg.qq.com, 110.43.90.61, zt.wps.cn, sapi.beingfine.cn, weibo.com, api.weibo.cn, pay.sc.weibo.com, e.189.cn, mkt.21cn.com, app.moutai519.com.cn, www.nodeseek.com

#Cookie获取成功后在重写里禁用掉本订阅
#Cookie失效时在重写里启用本订阅

# NobyDa
# 获取京东Cookie.
http-request ^https:\/\/(api\.m|me-api)\.jd\.com\/(client\.action\?functionId=signBean|user_new\/info\/GetJDUserInfoUnion\?) script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js, tag=获取京东Cookie

# 获取钢镚签到body.
http-request ^https:\/\/ms\.jr\.jd\.com\/gw\/generic\/hy\/h5\/m\/appSign\? script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js, requires-body=true, tag=获取钢镚签到body

# 爱奇艺获取cookie
http-request ^https:\/\/passport\.iqiyi\.com\/apis\/user\/info\.action script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js, tag=爱奇艺获取cookie

# Chavyleung

# 网易云签到获取cookie(by chavyleung)
http-request ^https:\/\/music.163.com\/weapi\/user\/level script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/quanx/neteasemusic.cookie.js, requires-body=true, tag=网易云签到获取cookie(by chavyleung)

# V2ex获取cookie
http-request ^https:\/\/www\.v2ex\.com\/mission\/daily script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/v2ex/quanx/v2ex.cookie.js, tag=V2ex获取cookie

# 腾讯视频获取cookie
http-request ^https:\/\/access.video.qq.com\/user\/auth_refresh script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/videoqq/videoqq.cookie.js, tag=腾讯视频获取cookie
http-request ^https?:\/\/v.qq.com\/x\/bu\/mobile_checkin script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/videoqq/videoqq.cookie.js, tag=腾讯视频获取cookie

# 人人视频获取cookie
http-request ^https:\/\/api\.rr\.tv\/user\/profile script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/rrtv/rrtv.cookie.js, tag=人人视频获取cookie

# 电信营业厅获取cookie
# 单独版 By chavyleung)
http-request ^https:\/\/wapside.189.cn:9001\/api\/home\/homeInfo script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10000/10000.cookie.js, requires-body=true, tag=单独版 By chavyleung)

# 美团
http-request ^https:\/\/i.meituan.com\/evolve\/signin\/signpost\/ script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.cookie.js, requires-body=true, tag=美团

# 全民K歌
http-request ^https://node\.kg\.qq\.com/webapp/proxy? script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/qmkg/qmkg.cookie.js, requires-body=true, tag=全民K歌

# WPS
http-request ^https:\/\/zt.wps.cn\/2018\/docer_check_in\/api\/act_list script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/wps/wps.cookie.js, tag=WPS

# 不背单词
http-request ^https:\/\/sapi\.beingfine\.cn\/v3\/bb\/reward\/by-sign-in script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bubei/bubei.js, tag=不背单词

# > 微博 (By @Macsuny)
http-request https:\/\/api\.weibo\.cn\/\d\/users\/show script-path=https://raw.githubusercontent.com/Sunert/Script/master/Task/weibo.js, tag=微博 (By @Macsuny)



# 电信套餐余量查询
http-request ^https?:\/\/e\.189\.cn\/store\/user\/package_detail\.do script-path=https://raw.githubusercontent.com/PoetryU/Scientist/master/Scripts/telecomInfinity.js, tag=电信套餐余量查询

# i 茅台
http-response https://app.moutai519.com.cn/xhr/front/user/info script-path=https://raw.githubusercontent.com/PoetryU/Scientist/master/Scripts/imaotai.js, requires-body=true, tag=i 茅台

# NodeSeek
http-request ^https:\/\/www\.nodeseek\.com\/api\/account\/getInfo\/\d+\?.*readme=1 script-path=https://raw.githubusercontent.com/PoetryU/Scientist/master/Scripts/NSCheckin_Loon.js, tag=NodeSeek
